- name: Install NPM dependencies
  shell: chdir=../frontend/reddit-monitor npm install

- name: package FrontEnd
  shell: chdir=../frontend/reddit-monitor npm run build

- name: Install dateutil for s3 module
  shell: pip install python-dateutil boto3

- name: Copy frontend bundle to target
  s3_sync:
    file_root: ../frontend/reddit-monitor/dist/
    bucket: cf-s3-reddit-monitor