- name: Install NPM dependencies
  shell: chdir=../frontend/reddit-monitor npm install

- name: package FrontEnd
  shell: chdir=../frontend/reddit-monitor npm run build

- name: Install dateutil and boto for s3 module
  shell: pip install python-dateutil boto3

- name: Copy frontend bundle to target
  s3_sync:
    file_root: ../frontend/reddit-monitor/dist/
    bucket: cf-s3-reddit-monitor
    region: eu-west-1
    permission: public-read
    exclude: index.html

- name: Force-no-cache on index
  s3:
    bucket: cf-s3-reddit-monitor
    object: index.html
    src: ../frontend/reddit-monitor/dist/index.html
    mode: put
    metadata: 'Cache-Control=no-cache'