- name: Install NPM dependencies
  run_once: true
  local_action: command chdir=../frontend/reddit-monitor npm install

- name: package FrontEnd
  run_once: true
  local_action: command chdir=../frontend/reddit-monitor npm run build

- name: Install dateutil for s3 module
  run_once: true
  local_action: command pip install python-dateutil

- name: Copy frontend bundle to target
  s3_sync:
    file_root: ../frontend/reddit-monitor/dist/
    bucket: cf-s3-reddit-monitor