- include: install-dotnet.yml

- name: Package NetCore bundle
  run_once: true
  local_action: command chdir=.. dotnet publish -c Release

- name: Copy NetCore bundle to target
  synchronize:
    src: ../src/KPI.RedditMonitor.Api/bin/Release/netcoreapp2.2/publish/
    dest: /home/ubuntu/redditmonitor/backend/

- name: Copy systemd service file
  become: true
  become_method: sudo
  template:
    src: redditmonitor.service.j2
    dest: /etc/systemd/system/redditmonitor.service

- name: Start redditmonitor service
  become: true
  become_method: sudo
  systemd:
    name: redditmonitor
    daemon_reload: yes
    state: restarted
    enabled: yes