- name: Package NetCore bundle
  run_once: true
  local_action: command chdir=.. dotnet publish -c Release
- name: Copy NetCore bundle to target
  synchronize:
    src: ../src/KPI.RedditMonitor.Api/bin/Release/netcoreapp2.2/publish
    dest: /home/ubuntu/redditmonitor
- include_tasks: install-dotnet.yml