- name: Package NetCore bundle
  run_once: true
  local_action: command chdir=.. dotnet publish -c Release
- name: Copy NetCore bundle to target
  copy:
    src: ../src/KPI.RedditMonitor/Release/netcore2.2/publish
    dest: /home/ubuntu/redditmonitor