---
- name: install python
  hosts: all
  pre_tasks:
  - raw: sudo apt-get -y install python-simplejson
  remote_user: ubuntu
  gather_facts: false

- name: deploy BE
  hosts: all
  remote_user: ubuntu
  roles:
    - backend
    - nginx

- name: deploy FE
  hosts: 127.0.0.1
  connection: local
  roles:
    - frontend